-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg94FqOUlOb/v/s3ZM
93MuYvZab/63oAbDTO1/qlmgEfOgCgYIKoZIzj0DAQehRANCAAT1vvV/XKdWIrYe
LdSFZePOSYI0b21XBks+9hXewbs0ddWhyONjciDu9lnsDwYK3NuaIsOrF7QYCnDw
STuKpa/M
-----END PRIVATE KEY-----