# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'React' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for React
  pod 'KakaoSDK'

  target 'ReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactUITests' do
    # Pods for testing
  end

end
