# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CirclinReact' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CirclinReact
  pod 'KakaoSDK'

  target 'CirclinReactTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CirclinReactUITests' do
    # Pods for testing
  end

end
