import type { AppProps } from "next/app";
import Head from "next/head";
import { RecoilRoot } from "recoil";
import { Global } from "@emotion/react";
import reset from "../styles/reset";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "../styles/themes/theme";
import Loader from "../components/atoms/loader";
import Dialog from "../components/atoms/dialog";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Global styles={reset} />
      <ThemeProvider theme={theme}>
        <RecoilRoot>
          <Component {...pageProps} />
          <Loader />
          <Dialog />
        </RecoilRoot>
      </ThemeProvider>
    </>
  );
}

export default MyApp;
