import { Container, createTheme, CssBaseline, ThemeProvider } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const theme = createTheme();

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>MY Project Name</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
          <CssBaseline />
          

        <Container component="main" maxWidth="xs">
        </Container>
      </ThemeProvider>
    </>
  )
}

export default Home
